export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN = "LOGIN";
export const REGISTER = "REGISTER";
export const START_LOADING_GUEST = "START_LOADING_GUEST";
export const END_LOADING_GUEST = "END_LOADING_GUEST";
